### PR TITLE
Fix the Semigroup instance for MarkupContent

### LINKED ISSUE #328: Semigroup instance for MarkupContent is wrong
Markdown and plaintext have different semantics wrt newlines. The current semigroup instance simply coerces plaintext to markdown, but this breaks newlines. A more correct solution would be to do something like this for any plaintext arguments that are being transformed into markdown:

```
forceMarkdownNewlines :: String -> String
forceMarkdownNewlines = unlines . fmap (<> "  ") . lines
```

### PR DESCRIPTION
**Pull request by michaelpj**
Fixes #328.

### CODE REVIEW

File: lsp-types/src/Language/LSP/Types/MarkupContent.hs [hunk 1]
```diff
@@ -81,10 +82,18 @@ sectionSeparator = "* * *\n"
 
 -- ---------------------------------------------------------------------
 
+-- | Given some plaintext, convert it into some equivalent markdown text.
+-- This is not *quite* the identity function.
+plainTextToMarkdown :: Text -> Text
+-- Line breaks in markdown paragraphs are ignored unless the line ends with two spaces.
```
Comment (pepeiborra) [inline lsp-types/src/Language/LSP/Types/MarkupContent.hs:88]: TIL

**Review by pepeiborra — APPROVED** [review]
